services:
  mongodb:
    image: mongo:5.0.15
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME: carsondev1
      - MONGO_INITDB_ROOT_PASSWORD: tinh123
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:

    # docker compose -p carsondev1-mongodb-4rn up -d
